//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceShuttleLaunch.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceShuttleLaunch.Localization.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null. Please try again. .
        /// </summary>
        internal static string CannotBeNull {
            get {
                return ResourceManager.GetString("CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client was not permitted to send the email..
        /// </summary>
        internal static string ClientNotPermitted {
            get {
                return ResourceManager.GetString("ClientNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading to the CSV file: {0}.
        /// </summary>
        internal static string CsvError {
            get {
                return ResourceManager.GetString("CsvError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A format error occurred while parsing the data: {0}.
        /// </summary>
        internal static string CsvFileFormatException {
            get {
                return ResourceManager.GetString("CsvFileFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An overflow error occurred while parsing the data: {0}.
        /// </summary>
        internal static string DataParsingError {
            get {
                return ResourceManager.GetString("DataParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current directory does not exist..
        /// </summary>
        internal static string DirectoryNotFoundException {
            get {
                return ResourceManager.GetString("DirectoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email was not sent. Please try again..
        /// </summary>
        internal static string EmailNotSent {
            get {
                return ResourceManager.GetString("EmailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the email: {0}.
        /// </summary>
        internal static string EmailNotSentError {
            get {
                return ResourceManager.GetString("EmailNotSentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the path to the folder on the file system:.
        /// </summary>
        internal static string EnterInputFolderPath {
            get {
                return ResourceManager.GetString("EnterInputFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the recipient email:.
        /// </summary>
        internal static string EnterInputRecipientEmail {
            get {
                return ResourceManager.GetString("EnterInputRecipientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the sender email:.
        /// </summary>
        internal static string EnterInputSenderEmail {
            get {
                return ResourceManager.GetString("EnterInputSenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the sender password:.
        /// </summary>
        internal static string EnterInputSenderPassword {
            get {
                return ResourceManager.GetString("EnterInputSenderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while writing to the CSV file..
        /// </summary>
        internal static string ErrorWritingToFile {
            get {
                return ResourceManager.GetString("ErrorWritingToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is too large to fit in the recipient&apos;s mailbox..
        /// </summary>
        internal static string ExceededStorageAllocation {
            get {
                return ResourceManager.GetString("ExceededStorageAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is already open in another process..
        /// </summary>
        internal static string FileAlreadyOpen {
            get {
                return ResourceManager.GetString("FileAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General failure when sending the email..
        /// </summary>
        internal static string GeneralFailure {
            get {
                return ResourceManager.GetString("GeneralFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address! Please try again: .
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password! Please try again. .
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid recipient email address! Please try again: .
        /// </summary>
        internal static string InvalidRecipientEmail {
            get {
                return ResourceManager.GetString("InvalidRecipientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IO error occurred: {0}.
        /// </summary>
        internal static string IOError {
            get {
                return ResourceManager.GetString("IOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is empty. Please try again. .
        /// </summary>
        internal static string IsEmpty {
            get {
                return ResourceManager.GetString("IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipient&apos;s mailbox is busy or unavailable..
        /// </summary>
        internal static string MailboxBusyOrUnavailable {
            get {
                return ResourceManager.GetString("MailboxBusyOrUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum number of attempts. Please try again later..
        /// </summary>
        internal static string MaxAttemptsReached {
            get {
                return ResourceManager.GetString("MaxAttemptsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model doesn&apos;t exist! It cannot be null..
        /// </summary>
        internal static string ModelCannotBeNull {
            get {
                return ResourceManager.GetString("ModelCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No forecasts available..
        /// </summary>
        internal static string NoForecastsAvailable {
            get {
                return ResourceManager.GetString("NoForecastsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a DailyForecast..
        /// </summary>
        internal static string NotADailyForecast {
            get {
                return ResourceManager.GetString("NotADailyForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough disk space to create or write to the file..
        /// </summary>
        internal static string NotEnoughDiskSpace {
            get {
                return ResourceManager.GetString("NotEnoughDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} path is not valid..
        /// </summary>
        internal static string PathIncorrect {
            get {
                return ResourceManager.GetString("PathIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the preferred language:.
        /// </summary>
        internal static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email transaction failed..
        /// </summary>
        internal static string TransactionFailed {
            get {
                return ResourceManager.GetString("TransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Space Shuttle Launch Program!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
